**1. Створення масивів**

Створіть (кожен пункт оцінюється в 0.5 бала):
- Масив зі списку `[5, 15, 25, 35, 45]`
- Масив з нулів розміром 7
- Масив з одиниць розміром 6
- Масив з числами від 10 до 19 використовуючи `np.arange()`

In [1]:
import numpy as np

In [3]:
arr = np.array([5, 15, 25, 35, 45])
arr

array([ 5, 15, 25, 35, 45])

In [4]:
arr1 = np.zeros(7)
arr1

array([0., 0., 0., 0., 0., 0., 0.])

In [5]:
arr2 = np.ones(6)
arr2

array([1., 1., 1., 1., 1., 1.])

In [7]:
arr3 = np.arange(10, 20)
arr3

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])


---

**2. Базові операції**

Створіть Numpy-масив зі значеннями [12, 24, 36, 48, 60].

Виконайте наступні операції над **оригінальним** масивом і запишіть у нову змінну результат (кожен пункт оцінюється в 0.5 бала):
- Помножте всі елементи на 2
- Додайте до всіх елементів 10
- Піднесіть всі елементи до квадрату
- Обчисліть квадратний корінь з усіх елементів

Виведіть результат виконання кожної операції.

In [10]:
np_array = np.array([12, 24, 36, 48, 60])
np_array

array([12, 24, 36, 48, 60])

In [11]:
np_array_new = np_array * 2
print(np_array_new)

[ 24  48  72  96 120]


In [12]:
np_array_new = np_array + 10
print(np_array_new)

[22 34 46 58 70]


In [13]:
np_array_new = np_array ** 2
print(np_array_new)

[ 144  576 1296 2304 3600]


In [14]:
np_array_new = np.sqrt(np_array)
print(np_array_new)

[3.46410162 4.89897949 6.         6.92820323 7.74596669]



---

**3. Статистичні функції**

Створіть Numpy-масив `data` зі значеннями [18, 27, 33, 41, 52, 68, 79].

Обчисліть використовуючи функціонал numpy (кожен пункт оцінюється в 0.5 бала):
- Середнє значення
- Мінімум
- Максимум
- Суму всіх елементів

In [15]:
data = np.array([18, 27, 33, 41, 52, 68, 79])

In [16]:
print(data.mean())
print(data.min())
print(data.max())
print(data.sum())

45.42857142857143
18
79
318



---

**4. Індексація**

Створіть Numpy-масив `arr` зі значеннями [15, 22, 35, 44, 58, 67].

Виведіть (кожен пункт оцінюється в 0.5 бала):
- Перший елемент
- Останній елемент
- Елементи з індексами 1 до 3
- Елементи більші за 40

In [17]:
arr = np.array([15, 22, 35, 44, 58, 67])

In [19]:
print(arr[0])
print(arr[-1])
print(arr[1:4])

mask = arr > 40
print(arr[mask])

15
67
[22 35 44]
[44 58 67]



---


**5. Двовимірні масиви**

Задано матрицю 3x3.

Виконайте наступні дії з функціоналом Numpy (кожен пункт оцінюється в 0.5 бала):
- Виведіть форму (shape) матриці
- Виведіть перший рядок
- Виведіть другу колонку
- Обчисліть суму всіх елементів
- Обчисліть середнє всіх елементів

In [20]:
matrix = np.array([[2, 4, 6],
                   [8, 10, 12],
                   [14, 16, 18]])

In [21]:
matrix.shape

(3, 3)

In [22]:
matrix[0, :]

array([2, 4, 6])

In [23]:
matrix[:, 1]

array([ 4, 10, 16])

In [24]:
matrix.sum()

np.int64(90)

In [25]:
matrix.mean()

np.float64(10.0)